#!/bin/bash

#PBS -m abe
#PBS -V
#PBS -l nodes=grad08:ppn=16:cluster-Grad,walltime=00:25:00
#PBS -M giuseppe.menti@edu.pucrs.br
#PBS -r n
#PBS -j oe
#PBS -d /home/pp12709/openmp/2020-02-closest_pair

echo Running on host `hostname`
echo Initial time is `date`
echo Directory is `pwd`
echo
echo This jobs runs on the following nodes:
echo `cat $PBS_NODEFILE | uniq`
echo
echo JOB_ID:
echo `echo $PBS_JOBID`

export OMP_NUM_THREADS=1
./solution 1> ./output/x1-saida 2> ./output/x1-tempos

export OMP_NUM_THREADS=2
./solution 1> ./output/x2-saida 2> ./output/x2-tempos

export OMP_NUM_THREADS=4
./solution 1> ./output/x4-saida 2> ./output/x4-tempos

export OMP_NUM_THREADS=8
./solution 1> ./output/x8-saida 2> ./output/x8-tempos

export OMP_NUM_THREADS=16
./solution 1> ./output/x16-saida 2> ./output/x16-tempos
